#!/usr/bin/env bash

export K9S_NEO_PROFILE="${K9S_NEO_PROFILE:-k9s-neo-metrics-small}"
export K9S_NEO_COLIMA_PROFILE="${K9S_NEO_COLIMA_PROFILE:-k9s-neo}"
export K9S_NEO_ENABLE_METRICS_SERVER="${K9S_NEO_ENABLE_METRICS_SERVER:-1}"
export K9S_NEO_DELETE_COLIMA_PROFILE="${K9S_NEO_DELETE_COLIMA_PROFILE:-0}"
